/*
 * Countries.h
 *
 *  Written by Ramata Soumounou
 * Comp 345-Assignment 1
 * Instructor: Joey Paquet
 * October 29, 2015
 */

#ifndef COUNTRIES_H_
#define COUNTRIES_H_


#include <string>
#include "Players.h"

enum CountriesName
{
ALGERIA, ANGOLA, BENIN, BOSTWANA, BURKINA_FASO, BURUNDI, CABO_VERDE, CAMEROON, CENTRAL_AFRICAN_REPUBLIC, CHAD, COMOROS, REPUBLIC_OF_CONGO, IVORY_COAST, DJIBOUTI, EGYPT, EQUATORIAL_GUINEA, ERITREA, ETHIOPIA, GABON, GAMBIA, GHANA, GUINEA, GUINEA_BISSAU, KENYA, LESOTHO, LIBERIA, LIBYA, MADAGASCAR, MALAWI, MALI, MAURITANIA, MAURITIUS, MOROCCO, MOZAMBIQUE, NAMIBIA, NIGER, NIGERIA, RWANDA, SENEGAL, SEYCHELLES, SIERRA_LEONE, SOMALIA, SOUTH_AFRICA, SOUTH_SUDAN, SUDAN, SWAZILAND, TANZANIA, ROGO, TUNISIA, UGANDA, ZAMBIA, ZIMBABWE,


AFGHANISTAN, ARMENIA, AZERBAIJAN, BAHRAIN, BANGLADESH. BHUTAN, BRUNEI, CAMBODIA, CHINA, CYPRUS, GEORGIA, INDIA, INDONESIA, IRAN, IRAQ, ISRAEL, JAPAN, JORDAN, KAZAKHSTAN, KUWAIT, KYRGYZSTAN, LAOS, LEBANON, MALAYSIA, MALDIVES, MONGOLIA, MYANMAR, NEPAL, NORTH_KOREA, OMAN, PAKISTAN, PALESTINE, PHILIPPINES, QATAR, RUSSIA, SAUDI_ARABIA, SINGAPORE, SOUTH_KOREA, SRI_LANKA, SYRIA, TAIWAN, TAJIKISTAN, THAILAND, TIMOR_LESTE, TURKEY, TURKMENISTAN, UNITED_ARAB_EMIRATES, UZBEKISTAN, VIETNAM, YEMEN,

ALBANIA, ANDORRA, ARMENIA, AUSTRIA, AZERBAIJAN, BELARUS, BELGIUM, BOSNIA_HERZEGOVINA, BULGARIA, CROATIA, CYPRUS, CZECH_REPUBLIC, DENMARK, ESTONIA, FINLAND, FRANCE, GEORGIA, GERMANY, GREECE, HUNGARY, ICELAND, IRELAND, ITALY, KAZAKHSTAN, KOSOVO, LATVIA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MACEDONIA, MALTA, MOLDOVA, MONACO, MONTENEGRO, NETHERLANDS, NORWAY, POLAND, PORTUGAL, ROMANIA, SAN_MARINO, SERBIA, SLOVAKIA, SLOVENIA, SPAIN, SWEDEN, SWITZERLAND, UKRAINE, UNITED_KINGDOM, VATICAN,

ANTIGUA_AND_BARBUDA, BAHAMAS, BARBADOS, BELIZE, CANADA, COSTA_RICA, CUBA, DOMINICA, DOMINICAN_REPUBLIC, EL_SALVADOR, GRENADA, GUATEMALA, HAITI, HONDURAS, JAMAICA, MEXICO, NICARAGUA, PANAMA, ST_LUCIA, TRINIDAD_AND_TOBAGO, USA,


ARGENTINA, BOLIVIA, BRAZIL, CHILE, COLOMBIA, ECUADOR, GUYANA, PARAGUAU, PERU, SURINAME, URUGUAY, VENEZUELA,

AUSTRALIA, FIJI, KIRIBATI, MARSHALL_ISLANDS, MICRONESIA, NAURU, NEW_ZEALAND, PALAU, PAPUA_NEW_GUINEA, SAMOA, SOLOMON_ISLANDS, TONGA, TUVALU, VANUATU

NUM_COUNTRIES = 199
};


class Countries{

	public:

		Countries();

		Countries(const int value);

		Countries(const std::string countryName, const std::string continentName, int numberOfArmies, Players* p);

		void setNumArmies(int newArmies);

		int getNumArmies();

		void setOwner(Players* newOwner);

		Players* getOwner();

		bool isOccupied();


	private:

		std::string country;

		int countryValue;

		std::string continent;

		int numArmies;

		Players* owner;


};

#endif /* COUNTRIES_H_ */
